import type { PreviewClass } from './classify';

// Every user-facing string of the view-only previews, in one place for a future translation pass.
export const PREVIEW_STRINGS = {
  kind: {
    image: 'image',
    'image-maybe': 'image',
    video: 'video',
    audio: 'audio',
    pdf: 'document',
    text: 'text',
    json: 'data',
    table: 'table',
    none: 'file',
  } satisfies Record<PreviewClass, string>,
  scrollRegion: (name: string) => `Contents of ${name}`,
  expandName: 'Show the full name',
  pdfLoading: 'Loading PDF…',
  pdfFailed: { title: "Can't show this PDF", body: "This PDF can't be shown in this browser." },
  pdfCapped: (max: number) => `Only the first ${max} pages are shown.`,
  pdfPages: (n: number) => (n === 1 ? '1 page' : `${n} pages`),
  pdfPage: (n: number, of: number) => `Page ${n} / ${of}`,
  pdfPageLabel: (name: string, n: number, of: number) => `${name}, page ${n} of ${of}`,
  pdfToolbar: 'PDF view',
  pdfZoomIn: 'Zoom in',
  pdfZoomOut: 'Zoom out',
  pdfFitWidth: 'Width',
  pdfFitWidthLabel: 'Fit page width',
  pdfFitPage: 'Page',
  pdfFitPageLabel: 'Fit whole page',
  zoomPercent: (n: number) => `${Math.round(n * 100)}%`,
  imageFailed: { title: "Can't show this image", body: "This image can't be shown in this browser." },
  heicFailed: {
    title: "Can't show this photo here",
    body: "This photo couldn't be decoded in this browser. Safari on iPhone, iPad or Mac can show it.",
  },
  tiffFailed: {
    title: "Can't show this photo here",
    body: "This photo format can't be shown in this browser. Safari on iPhone, iPad or Mac can show it.",
  },
  videoFailed: { title: "Can't play this video", body: "This video can't be played in this browser." },
  audioFailed: { title: "Can't play this audio", body: "This audio can't be played in this browser." },
  tableCapped: (max: number) => `Only the first ${max} rows are shown.`,
  tableColumns: (n: number) => (n === 1 ? '1 column' : `${n} columns`),
  tableScrollHint: 'scroll',
  truncated: 'Truncated: only the first 2 MB are shown.',
  unavailableTitle: 'Preview not available',
  unavailableBody: "This file type can't be previewed in a browser. View-only drops don't offer downloads.",
};
