name: 'Feed to netlify'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/feed-app/src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_SITE_ID: 2ad91e6e-3439-40ef-842b-80380912b1e3
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: npm install
          build_command: npm run build -w packages/feed-app
          build_directory: packages/feed-app/dist
