name: Publish js-lib Prerelease to Github Packages
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - 'main'
    paths:
      - 'packages/lib/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'

      # Set git User & Bump the version: https://docs.npmjs.com/cli/v8/commands/npm-version
      - name: Bump version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version prerelease --w ./packages/lib

      - run: npm ci

      - run: npm run build --w ./packages/lib

      - run: npm publish --w ./packages/lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the version increment back into the repo
      - name: Bump version updates
        run: |
          git commit -am "Bump version"
          git push
